//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadCallCenterOrderData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_Cuore_Order_Details
    {
        public long id { get; set; }
        public int orderid { get; set; }
        public int productid { get; set; }
        public decimal price { get; set; }
        public int amount { get; set; }
        public int provider { get; set; }
        public string product_options { get; set; }
        public Nullable<int> itemid { get; set; }
        public string productcode { get; set; }
        public string product { get; set; }
        public int date { get; set; }
    }
}
