//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadCallCenterOrderData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERHEADER
    {
        public decimal CUSTEDP { get; set; }
        public string FULLORDERNO { get; set; }
        public string COMPANY { get; set; }
        public string DIVISION { get; set; }
        public string SOURCE { get; set; }
        public string MAILDATE { get; set; }
        public string ENTRYDATE { get; set; }
        public string ENTRYTIME { get; set; }
        public string REMITDATE { get; set; }
        public string ENTRYOPER { get; set; }
        public string PAYMETHOD { get; set; }
        public decimal PRODUCTDOLLARS { get; set; }
        public decimal ITEMCOUNT { get; set; }
        public string FLAGS { get; set; }
        public string DISCOUNTCODES { get; set; }
        public decimal SHIPITEMCOUNT { get; set; }
        public decimal SHIPMENTCOUNT { get; set; }
        public string LASTSHIPMENT { get; set; }
        public decimal AUDITDATES_001 { get; set; }
        public decimal AUDITDATES_002 { get; set; }
        public decimal AUDITDATES_003 { get; set; }
        public decimal AUDITDATES_004 { get; set; }
        public decimal AUDITDATES_005 { get; set; }
        public decimal AUDITDATES_006 { get; set; }
        public decimal AUDITDATES_007 { get; set; }
        public decimal AUDITDATES_008 { get; set; }
        public decimal AUDITDATES_009 { get; set; }
        public decimal AUDITDATES_010 { get; set; }
        public string STATUS { get; set; }
        public decimal COUNTRYCMP { get; set; }
        public string FLAGS2 { get; set; }
        public string SUPPRESSLETTERS { get; set; }
        public decimal FIFONO { get; set; }
        public decimal SLOTID { get; set; }
    }
}
