//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadCallCenterOrderData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSystemParameterValue
    {
        public int SystemParameterValuesId { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
        public string ParameterDescription { get; set; }
        public string GroupId { get; set; }
        public System.DateTime dt_Created { get; set; }
        public System.DateTime dt_Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
